name: Knot
options:
  bundleIdPrefix: com.knot
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  groupSortPosition: top

packages:
  LucideIcons:
    url: https://github.com/JakubMazur/lucide-icons-swift.git
    from: "0.563.1"
  Supabase:
    url: https://github.com/supabase/supabase-swift.git
    from: "2.0.0"

settings:
  base:
    SWIFT_VERSION: "6.0"
    SWIFT_STRICT_CONCURRENCY: complete
    ENABLE_USER_SCRIPT_SANDBOXING: true
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
    INFOPLIST_FILE: Knot/Info.plist
    PRODUCT_BUNDLE_IDENTIFIER: com.ronniejay.knot
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: VN5G3R8J23
    CODE_SIGN_STYLE: Automatic

targets:
  Knot:
    type: application
    platform: iOS
    sources:
      - path: Knot
        excludes:
          - "**/.DS_Store"
    entitlements:
      path: Knot/Knot.entitlements
      properties:
        com.apple.developer.applesignin:
          - Default
    settings:
      base:
        INFOPLIST_FILE: Knot/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.ronniejay.knot
        SWIFT_EMIT_LOC_STRINGS: true
        GENERATE_INFOPLIST_FILE: false
        CODE_SIGN_ENTITLEMENTS: Knot/Knot.entitlements
    dependencies:
      - package: LucideIcons
      - package: Supabase
        product: Auth
      - package: Supabase
        product: PostgREST
      - package: Supabase
        product: Supabase
    preBuildScripts: []
    postBuildScripts: []

  KnotTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: KnotTests
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.ronniejay.knot.tests
        GENERATE_INFOPLIST_FILE: true
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Knot.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/Knot"
        BUNDLE_LOADER: "$(TEST_HOST)"
    dependencies:
      - target: Knot

  KnotUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: KnotUITests
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.ronniejay.knot.uitests
        GENERATE_INFOPLIST_FILE: true
        TEST_TARGET_NAME: Knot
    dependencies:
      - target: Knot

schemes:
  Knot:
    build:
      targets:
        Knot: all
        KnotTests: [test]
        KnotUITests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - KnotTests
        - KnotUITests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
